### ISSUE TITLE
feature: gossip observed new heads not seen from gossip

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#100]
if the index observes a new head either when polling or from http, it could gossip out the update as a way to help other indexers reduce their latency in observing the new content.

**Comment by gammazero** [comment]
This should be optional behavior, because I may want to sync an indexer to a publisher, but do not want other indexers syncing to that publisher.

An alternative is for an indexer to query the `/providers` endpoint of another indexer.  If the responding indexer has providers that are unknown to the querying indexer or has providers with unseen advertisements, then the querying indexer can perform a sync to those providers (to their publishers).
