### ISSUE TITLE
runtime updates to config

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#485]
would be great to be able push ratelimiting and allow-list config changes during runtime without needing to restart the indexer

**Comment by masih** [comment]
For config to change without triggering redeployment 2 things need to get done:
1. application level reloading of content, say from watching the config file and reflecting any update at runtime.
2. change in the manifests to use a fixed ConfigMap name such that when the config changes the statefulset manifests does not change. It changes today because we generate the ConfigMap using a generator and that, by convention, concatenates a short SHA of content to the name of ConfigMap. This is a common practice since in a typical case one would want the pods to rotate when config changes.

@gammazero I can take the second item.

**Comment by willscott** [comment]
the http endpoint PR  @gammazero made provides #1 as i understand it

**Comment by masih** [comment]
#551 completed the item 2. Closing.
